trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.6'
 
- script: |
    gem install jekyll bundler
    bundle install --retry=3 --jobs=4
  displayName: 'Install Jekyll'
 
- script: |
    bundle install
    jekyll -v
    jekyll build
  displayName: 'Build Jekyll Site'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1
      mv azcopy azcopy10
      azcopy10 --version
      azcopy10 sync "./_site/" "https://rootisgodstaticwebsite.blob.core.windows.net/`$web$env:SASTOKEN" --delete-destination true
    displayName: 'Update Static Site Blob'
  env:
    SASTOKEN: $(sastoken)

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(0557bba5-5cab-4a81-9c29-bd557b67a8e2)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az cdn endpoint purge --resource-group "www.rootisgod.com" --name "rootisgod" --profile-name "rootisgod-cdn" --content-paths "/*"'
  displayName: 'Purge CDN Cache'    